project:
  type: website
  output-dir: ../docs

website:
  title: "IUCN RLE for the forest of the Americas"
  repo-url: https://github.com/red-list-ecosystem/RLE-forests-panam-results
  repo-branch: mostly-harmless
  repo-actions: [edit, issue]
  navbar:
    title: "RLE forests of the Americas"
    type: inverse
    left:
      - text: "{{< fa gear >}} Home"
        icon: fa-home
        href: index.qmd
      - text: "{{< fa landmark >}} Ecosystem classification"
        menu:
          - text: "IVC / EcoVeg"
            href: continental-ecos.qmd
      - text: "{{< fa leaf >}} Results by formation"
        menu:
          - text: "Tropical dry forest"
<<<<<<< HEAD
            href: continental-1.A.1/mcdg-list.qmd
          - text: "Temperate flooded forest"
            href: continental-1.B.3/mcdg-list.qmd
=======
            href: continental/1.A.1/mcdg-list.qmd
          - text: "Temperate flooded forest"
            href: continental/1.B.3/mcdg-list.qmd
>>>>>>> 5fe978e37a86c8b8634434af824b2cd7836f2f41
      - text: "{{< fa globe >}} Results by country"
        menu:
          - text: "South America"
            href: countries-SAM/country-list.qmd
    right:
      - text: "How to..."
        icon: question
        menu:
          - text: "(re-)create this site"
            href: notes.qmd
bibliography: 
  - RLE.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



